# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b934d2869283a94f098d4cf9d830d48a31910f2d2db4cb15f80cd2ed4509ecbef433f9c3dc0561a638179693bc965546bfe27de4a58769cc0fed97031b79130a

test:
  secret_key_base: 822d78fe2f6200cae1cb07fcc2c21ede7fdd304afa60435f55b37999beefbb262809003bb72a450a21612e05043c29e30aaa36edd32d47c3693dee8976a2ff52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
